import React from 'react'
import * as pages from '../../../index.ts'

function questionArea() {
  return (
    <div className='bg-[#1c261a] p-2 rounded-md mb-4 max-w-[75%]'>
      Lorem, ipsum dolor sit amet consectetur adipisicing elit. Porro consequuntur amet distinctio? Consequuntur earum nisi aperiam repellat quis dolor error dolore nemo ipsam, vel quas odit porro atque quos odio! Tenetur labore rem at unde repellat maxime iusto consequatur quidem dolorem temporibus? Unde officia sequi aut veritatis. Sed iste consequatur corporis at esse minima temporibus dicta saepe animi, impedit ab veritatis autem similique aliquam magni a cupiditate repellendus velit. Nihil id unde nostrum cupiditate sint quam temporibus enim? Pariatur veritatis optio sed nemo dignissimos cumque, provident laboriosam officiis minus omnis nulla ab debitis voluptatem, tenetur aperiam! Sunt magnam praesentium reprehenderit, velit aut odio dolores veritatis eos assumenda at id dicta quae molestiae, modi voluptate sed! Vel laborum ad animi expedita, dolore repellendus quisquam iusto atque ipsum voluptas amet excepturi in doloribus veritatis molestias natus assumenda obcaecati soluta esse nesciunt repudiandae eligendi quasi est dolorem. Eos consequatur tenetur, fugit tempore possimus inventore, vitae est aliquid sequi, ipsum repellendus blanditiis corporis delectus et assumenda quidem eaque id suscipit rerum. Quae placeat ex similique quis dignissimos ut corrupti ullam adipisci eligendi vel asperiores ipsum aliquam incidunt, odio doloremque distinctio quam sed voluptas eius iste. Aspernatur, dolorum nostrum! Necessitatibus rem eveniet animi quasi deleniti eligendi, sunt delectus ea explicabo hic dolores maiores laborum magnam voluptatibus, molestiae commodi ab nam nostrum repellendus autem obcaecati ad? Accusantium provident esse alias dolorum distinctio minus neque quas quam iusto est vel velit iste praesentium veniam eius totam voluptatum, placeat molestiae laudantium sequi expedita soluta amet! Ipsum, vero quod cupiditate iusto cumque dicta debitis suscipit magni amet voluptate corrupti sed qui. Aperiam porro rerum commodi omnis odit reiciendis, molestiae asperiores, nam inventore aliquid totam magni modi assumenda adipisci et nihil quo recusandae, odio doloremque illum! Dolorum harum voluptates nostrum tempora dolore maiores numquam, rem laborum eveniet dignissimos ea at.
    </div>
  )
}

export default questionArea
