const theme = localStorage.getItem("toolpad-mode");
export { theme };
export { default as ChatBot } from "./pages/ChatBot/chatBot.tsx";
export { default as Dashboard } from "./pages/Dashboard";
export { default as App } from "./App.tsx";
export { default as ChattingPage } from "./pages/ChatBot/chattingPage.tsx";
export { default as inputArea } from "./pages/ChatBot/components/inputArea.tsx";
export { default as questionArea } from "./pages/ChatBot/components/questionArea.tsx";
export { default as responseArea } from "./pages/ChatBot/components/responseArea.tsx";
export { default as Chats } from "./pages/ChatBot/Chats.tsx";
